AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  amplify-console-notification

  SAM Template for amplify-console-notification
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  AmplifySNSTopicArn:
    Type: String
    Description: SNS Topic arn to subscribe amplify notifications.
  SenderType:
    Type: String
    Description: Type of Chat Service.
    AllowedValues: 
      - slack
      - idobata
    Default: slack
  WebHookURL:
    Type: String
    Description: WebHook URL.

Metadata:
  AWS::ServerlessRepo::Application:
    Name: amplify-console-notification
    Description: "Sends notifications about Amplify Console to a Slack channel. Support chat: - Slack https://slack.com - Idobata https://idobata.io"
    Author: fossamagna
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['amplify', 'slack', 'idobata']
    HomePageUrl: https://github.com/fossamagna/amplify-console-notification
    SemanticVersion: 1.1.1
    SourceCodeUrl: https://github.com/fossamagna/amplify-console-notification

Resources:
  NotificationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: notification
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        AmplifyNotificatoin:
          Type: SNS # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Topic: !Ref AmplifySNSTopicArn
      Environment:
        Variables:
          SENDER_TYPE: !Ref SenderType
          WEBHOOK_URL: !Ref WebHookURL

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  NotificationFunction:
    Description: "Notification Lambda Function ARN"
    Value: !GetAtt NotificationFunction.Arn
  NotificationFunctionIamRole:
    Description: "Implicit IAM Role created for Notification function"
    Value: !GetAtt NotificationFunctionRole.Arn
